---
framework: jest
tier: large
postMerge:
  pattern:
    - "./test/utils/warning.spec.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/utils/warning.spec.js"
preRun:
     command:
        - npm install
        - npm run build
postRun:
     command:
        - node --version
version: 2.3
