---
framework: jest
licenseTier: xsmall
postMerge:
  pattern:
    - "./test/**/*.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.ts"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.1
